# Generated by Django 3.2.4 on 2021-06-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website_app', '0003_auto_20210623_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
